"""initial schema

Revision ID: 95a6929f83a4
Revises: 
Create Date: 2026-07-31 03:05:07.213801

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = '95a6929f83a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('fake_pin_hash', sa.String(length=255), nullable=True),
    sa.Column('power_button_trigger_enabled', sa.Boolean(), nullable=False),
    sa.Column('gesture_trigger_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('devices',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('push_token', sa.String(length=500), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_user_id'), 'devices', ['user_id'], unique=False)
    op.create_table('journeys',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('destination_label', sa.String(length=255), nullable=False),
    sa.Column('destination_lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('destination_lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('expected_minutes', sa.Integer(), nullable=False),
    sa.Column('grace_minutes', sa.Integer(), nullable=False),
    sa.Column('expected_arrival_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_checkin_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notify_contact_ids', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('status', sa.Enum('active', 'arrived', 'escalated', 'cancelled', name='journey_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journeys_status'), 'journeys', ['status'], unique=False)
    op.create_index(op.f('ix_journeys_user_id'), 'journeys', ['user_id'], unique=False)
    op.create_table('trusted_contacts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('relationship_label', sa.String(length=60), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trusted_contacts_user_id'), 'trusted_contacts', ['user_id'], unique=False)
    op.create_table('sos_events',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('journey_id', sa.UUID(), nullable=True),
    sa.Column('trigger', sa.Enum('button', 'fake_pin', 'power_button', 'gesture', 'journey_timeout', name='sos_trigger'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'resolved', 'cancelled', name='sos_status'), nullable=False),
    sa.Column('origin_lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('origin_lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('audio_recording_url', sa.String(length=500), nullable=True),
    sa.Column('cancel_window_ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['journey_id'], ['journeys.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sos_events_status'), 'sos_events', ['status'], unique=False)
    op.create_index(op.f('ix_sos_events_user_id'), 'sos_events', ['user_id'], unique=False)
    op.create_table('location_pings',
    sa.Column('journey_id', sa.UUID(), nullable=True),
    sa.Column('sos_event_id', sa.UUID(), nullable=True),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('lng', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('accuracy_m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['journey_id'], ['journeys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sos_event_id'], ['sos_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_pings_journey_id'), 'location_pings', ['journey_id'], unique=False)
    op.create_index(op.f('ix_location_pings_sos_event_id'), 'location_pings', ['sos_event_id'], unique=False)
    op.create_table('sos_alert_deliveries',
    sa.Column('sos_event_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('push', 'sms_twilio', 'sms_termii', 'call', name='alert_channel'), nullable=False),
    sa.Column('status', sa.Enum('queued', 'sent', 'delivered', 'failed', name='alert_status'), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('provider_ref', sa.String(length=120), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['trusted_contacts.id'], ),
    sa.ForeignKeyConstraint(['sos_event_id'], ['sos_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sos_alert_deliveries_sos_event_id'), 'sos_alert_deliveries', ['sos_event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sos_alert_deliveries_sos_event_id'), table_name='sos_alert_deliveries')
    op.drop_table('sos_alert_deliveries')
    op.drop_index(op.f('ix_location_pings_sos_event_id'), table_name='location_pings')
    op.drop_index(op.f('ix_location_pings_journey_id'), table_name='location_pings')
    op.drop_table('location_pings')
    op.drop_index(op.f('ix_sos_events_user_id'), table_name='sos_events')
    op.drop_index(op.f('ix_sos_events_status'), table_name='sos_events')
    op.drop_table('sos_events')
    op.drop_index(op.f('ix_trusted_contacts_user_id'), table_name='trusted_contacts')
    op.drop_table('trusted_contacts')
    op.drop_index(op.f('ix_journeys_user_id'), table_name='journeys')
    op.drop_index(op.f('ix_journeys_status'), table_name='journeys')
    op.drop_table('journeys')
    op.drop_index(op.f('ix_devices_user_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
